<?php

/**
 * @file
 * Contains harvest_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function harvest_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the harvest_api module.
    case 'help.page.harvest_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Harvest API wrapper') . '</p>';
      return $output;

    default:
  }
}
